### PR TITLE
Improve mathjax handling

### LINKED ISSUE #34: Margin content in feed.xml
Howdy.

When `feed.xml` is created the content is provided by

       <description>{{ post.content | xml_escape }}</description>

However, the side margin information is included in the `post.content` which - for footnotes and references - can make the text rather unreadable. Is it possible to only get the content corresponding to the main column (i.e,. the content you can see for the smallest screen)?

### PR DESCRIPTION
**Pull request by xHN35RQ**

### CODE REVIEW

**Comment by xHN35RQ** [comment]
This isn't the best way to handle this... just an interim. It would be better to move all marginnote and sidenote content into footnotes for feed.xml. This way if someone is reading the site via a feed reader, they could still see the content at the bottom of each article.

**Comment by clayh53** [comment]
I agree. Let me stew on this a bit. I think the marginnote and sidenote content ought to remain in the feed, and it is just a matter of where it should go.

**Comment by xHN35RQ** [comment]
OK. Let me pull that out into a branch, and make this PR about mathjax.

**Comment by xHN35RQ** [comment]
As of now this PR enables `$` for inline equations, and lets people toggle it on and off. Also remove `.jekyll-metadata` and cleans up plugin commenting.

Since mathjax is part of kram-down your plugin for that is not needed. Do you want to delete it? If so, the Readme should be updated regarding mathjax usage.

**Pull request closed without merging**
